### ISSUE TITLE
help ，i don't know how to use your code

### ISSUE THREAD

**Issue by Youarerare** [allanj/ner_with_dependency#3]
I am a beginner and I think your code is very helpful to me. I want to know how I can successfully run your code. I think I am missing some files, but I don’t know exactly which ones and where to get them

**Comment by allanj** [comment]
Hi, sorry that I haven't updated the details yet due to the ACL deadline (but I will update the details once the deadline passes).

Can you post the error that you got while running the code?

Basically, you can use the latest version of PyTorch.

**Comment by Youarerare** [comment]
thank you, the error is :
Reading file: data/ontonotes/train.sd.conllx
Traceback (most recent call last):
  File "main.py", line 322, in <module>
    main()
  File "main.py", line 260, in main
    trains = reader.read_conll(conf.train_file, -1, True)
  File "/data/private/syk/ner_with_dependency/config/reader.py", line 25, ins read_conll
    with open(file, 'r', encoding='utf-8') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/ontonotes/train.sd.conllx'

I wonder if I should get the OntoNotes 5.0 English dataset and put it in the /data/ontonotes .
Now I am applying for the LDC license for several days. Thank you anyway.

**Comment by allanj** [comment]
Hi, thanks for your question.

I have uploaded the public available `catalan` and `spanish` dataset. You can simply replace the dataset argument with the above two datasets. It should work well.

If you have the LDC license, please send a screenshot to my email as well. I can send the data to you or send you the preprocessing script. 

Let me know if there are any other issues.

**Comment by Youarerare** [comment]
Your code is working very well now！
I am still waiting for permission.I found your email address from the issue that was closed before, and I will contact you once I get permission. Thank you for your help!
