### ISSUE TITLE
How to use Chinese data

### ISSUE THREAD

**Issue by BillKiller** [allanj/ner_with_dependency#7]
I saw that you use Chinese corpus  on OntoNotes ,so i am wandering how to use Chinese corpus.When i use Chinese corpus , it seem that some words will be packed together ,which may have  different slot.How do you cope with this problem. Your rapid reply will be highly appreciated. Thx.

**Comment by allanj** [comment]
What do you mean by "words" will be packed together?

So, from what I understand, Chinese words consist of one or more Chinese characters.
The dataset format is represented by words. Thus, I use the Chinese word embedding to encode

**Comment by BillKiller** [comment]
In dependency tree ,Chinese node is a word which has one or more Chinese characters.For example,  “我爱中国"  may has edge between "我" and "中国" . Sometimes characters not always share same slots . it may have different slot in "中国" . How do you cope with this problem.Split word into characters and assume them share some edges?

**Comment by BillKiller** [comment]
Do you mean that the slots in  OntoNotes-Chinese Corpus in word level rather that character level?

**Comment by allanj** [comment]
Yes. Right. They are word-level format.

**Comment by BillKiller** [comment]
Thx a lot.

**Comment by BillKiller** [comment]
Thx a lot.
